{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-phpfpm.serviceAccountName" . }}
  labels:
    {{- include "nginx-phpfpm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
{{- with .Values.serviceAccount.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- if .Values.dockerConfigJson }}
  - name: {{ include "nginx-phpfpm.fullname" . }}-registry
{{- end }}
{{- end }}
