{{- $chart_name := include "nginx-phpfpm.fullname" . }}
{{- $chart_labels := include "nginx-phpfpm.labels" . }}

{{- if .Values.configMaps }}
{{- range $name, $map := .Values.configMaps }}
{{- $checksum := toYaml $map | sha256sum | trunc 20 | quote }}
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ $chart_name }}-{{ $name }}
  labels:
    {{- $chart_labels | nindent 4 }}
  annotations:
    values/checksum: {{ $checksum }}
data:
  {{- range $name, $value := $map.data }}
  {{ $name }}: |
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $name, $path := $map.files }}
  {{ $name }}: |
    {{- $.Files.Get $path | nindent 4}}
  {{- end }}
{{- end }}
{{- end }}
