{{- if .Values.serviceAccount.create -}}
{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cronjobs.roleName" . }}
  namespace: {{ include "cronjobs.namespace" . }}
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- $rules := .Values.role.rules | required ".Values.role.rules is required if role is to be created." }}
{{- with $rules }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cronjobs.roleBindingName" . }}
  namespace: {{ include "cronjobs.namespace" . }}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: {{ include "cronjobs.serviceAccountName" . }}
  namespace: {{ include "cronjobs.namespace" . }}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: {{ include "cronjobs.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}

