apiVersion: v2
name: cronjobs
description: A generic helm cronjob chart for kubernetes
type: application
version: 0.0.6
appVersion: latest
home: https://github.com/DrPsychick
keywords:
  - cronjob
sources:
  - https://github.com/DrPsychick/charts
maintainers:
  - name: DrPsychick
    email: drpsychick@drsick.net
    url: https://github.com/DrPsychick
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/docker-library/busybox
    - name: Image DockerHub
      url: https://hub.docker.com/_/busybox
