# values for autoscaling
# test with `siege -d 1 -t 120S -c 5 http://localhost/load.php`

configMaps:
  scripts:
    path: /
    data:
      livez.html: |
        <html><body>OK</body></html>
      healthz.php: |
        <?php phpinfo(); ?>
      load.php: |
        <?php $time=time()+rand(1, 5); for(true;time() < $time;); phpinfo(); ?>

autoscaling:
  apiVersionOverride: autoscaling/v2

nginx:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 0.2
      memory: 50Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

phpfpm:
#  image:
#    tag: 8-fpm-bullseye
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  resources:
    limits:
      cpu: 1.5
      memory: 250Mi
    requests:
      cpu: 0.5
      memory: 100Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost
      paths:
        - path: "/"
